docs: fix MCP Server install command (#25)
With previous command, the install throws error:

```bash
$>pip install git+https://projects.blender.org/lab/blender_mcp.git
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://projects.blender.org/lab/blender_mcp.git
  Cloning https://projects.blender.org/lab/blender_mcp.git to /tmp/pip-req-build-d4wi95qo
  Running command git clone --filter=blob:none --quiet https://projects.blender.org/lab/blender_mcp.git /tmp/pip-req-build-d4wi95qo
  Resolved https://projects.blender.org/lab/blender_mcp.git to commit 03004fd0216bfe5e0a3d9ac9b47d5efadc3d78c4
ERROR: git+https://projects.blender.org/lab/blender_mcp.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

This fixes it.

Co-authored-by: ra100 <git@ra100.net>
Reviewed-on: https://projects.blender.org/lab/blender_mcp/pulls/25